; Assembler generated listing; Not editable.
; Generated by GNUSim8085: http://www.gnusim8085.org/
4200 3A 78  1	 lda 178H
4203 21 88  1	 lxi h,188H
4206 46 	 mov b,m
4207 11 89  1	 lxi d,189H
420A 4E 	 mov c,m
420B 80 	 add b
420C 81 	 add c
420D 76 	 hlt
