; Assembler generated listing; Not editable.
; Generated by GNUSim8085: http://www.gnusim8085.org/
4200 2A 00 040	 LHLD 4000H
4203 EB  	 XCHG
4204 2A 02 040	 LHLD 4002H
4207 7B  	 MOV A,E
4208 85  	 ADD L
4209 6F  	 MOV L,A
420A 7A  	 MOV A,D
420B 8C  	 ADC H
420C 67  	 MOV H,A
420D 22 04 040	 SHLD 4004H
4210 76  	 HLT
