; Assembler generated listing; Not editable.
; Generated by GNUSim8085: http://www.gnusim8085.org/
   	 ;Program for finding the 1's complement of a number
4200 3A 00 090	 LDA 9000H
4203 2F  	 CMA
4204 32 01 090	 STA 9001H
4207 76  	 HLT
