; Assembler generated listing; Not editable.
; Generated by GNUSim8085: http://www.gnusim8085.org/
4200 2A 00 040	 LHLD 4000H
4203 EB  	 XCHG
4204 2A 02 040	 LHLD 4002H
4207 19  	 DAD D
4208 22 04 040	 SHLD 4004H
420B 76  	 HLT
