; Assembler generated listing; Not editable.
; Generated by GNUSim8085: http://www.gnusim8085.org/
   	 ;Compare two 8 bit numbers stored at 2000H & 2001H
   	 ;using a subroutine to find the greater number
   	 ;and store at 2002H
4200 21 00 020	 LXI H,2000H
4203 46  	 MOV B,M
4204 23  	 INX H
4205 4E  	 MOV C,M
4206 CD 0C 042	 CALL MAX
4209 23  	 INX H
420A 77  	 MOV M,A
420B 76  	 HLT
420C 78  	 MAX: MOV A,B
420D B9  	 CMP C
420E D2 12 42	 JNC L1
4211 79  	 MOV A,C
4212 C9  	 L1: RET
